#ifndef BLUEFI_READER_H
#define BLUEFI_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct WifiCredentials_table *WifiCredentials_table_t;
typedef struct WifiCredentials_table *WifiCredentials_mutable_table_t;
typedef const flatbuffers_uoffset_t *WifiCredentials_vec_t;
typedef flatbuffers_uoffset_t *WifiCredentials_mutable_vec_t;
typedef const struct BluefiCommand_table *BluefiCommand_table_t;
typedef struct BluefiCommand_table *BluefiCommand_mutable_table_t;
typedef const flatbuffers_uoffset_t *BluefiCommand_vec_t;
typedef flatbuffers_uoffset_t *BluefiCommand_mutable_vec_t;
typedef const struct BluefiReply_table *BluefiReply_table_t;
typedef struct BluefiReply_table *BluefiReply_mutable_table_t;
typedef const flatbuffers_uoffset_t *BluefiReply_vec_t;
typedef flatbuffers_uoffset_t *BluefiReply_mutable_vec_t;
#ifndef WifiCredentials_file_identifier
#define WifiCredentials_file_identifier 0
#endif
/* deprecated, use WifiCredentials_file_identifier */
#ifndef WifiCredentials_identifier
#define WifiCredentials_identifier 0
#endif
#define WifiCredentials_type_hash ((flatbuffers_thash_t)0x95c39b0e)
#define WifiCredentials_type_identifier "\x0e\x9b\xc3\x95"
#ifndef WifiCredentials_file_extension
#define WifiCredentials_file_extension "bin"
#endif
#ifndef BluefiCommand_file_identifier
#define BluefiCommand_file_identifier 0
#endif
/* deprecated, use BluefiCommand_file_identifier */
#ifndef BluefiCommand_identifier
#define BluefiCommand_identifier 0
#endif
#define BluefiCommand_type_hash ((flatbuffers_thash_t)0x9e69c401)
#define BluefiCommand_type_identifier "\x01\xc4\x69\x9e"
#ifndef BluefiCommand_file_extension
#define BluefiCommand_file_extension "bin"
#endif
#ifndef BluefiReply_file_identifier
#define BluefiReply_file_identifier 0
#endif
/* deprecated, use BluefiReply_file_identifier */
#ifndef BluefiReply_identifier
#define BluefiReply_identifier 0
#endif
#define BluefiReply_type_hash ((flatbuffers_thash_t)0xc0aa36fc)
#define BluefiReply_type_identifier "\xfc\x36\xaa\xc0"
#ifndef BluefiReply_file_extension
#define BluefiReply_file_extension "bin"
#endif



struct WifiCredentials_table { uint8_t unused__; };

static inline size_t WifiCredentials_vec_len(WifiCredentials_vec_t vec)
__flatbuffers_vec_len(vec)
static inline WifiCredentials_table_t WifiCredentials_vec_at(WifiCredentials_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(WifiCredentials_table_t, vec, i, 0)
__flatbuffers_table_as_root(WifiCredentials)

__flatbuffers_define_string_field(0, WifiCredentials, ssid, 0)
__flatbuffers_define_string_field(1, WifiCredentials, password, 0)

struct BluefiCommand_table { uint8_t unused__; };

static inline size_t BluefiCommand_vec_len(BluefiCommand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline BluefiCommand_table_t BluefiCommand_vec_at(BluefiCommand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(BluefiCommand_table_t, vec, i, 0)
__flatbuffers_table_as_root(BluefiCommand)

__flatbuffers_define_table_field(0, BluefiCommand, wifiCredential, WifiCredentials_table_t, 0)
__flatbuffers_define_scalar_field(1, BluefiCommand, doScan, flatbuffers_int32, int32_t, INT32_C(0))

struct BluefiReply_table { uint8_t unused__; };

static inline size_t BluefiReply_vec_len(BluefiReply_vec_t vec)
__flatbuffers_vec_len(vec)
static inline BluefiReply_table_t BluefiReply_vec_at(BluefiReply_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(BluefiReply_table_t, vec, i, 0)
__flatbuffers_table_as_root(BluefiReply)

__flatbuffers_define_vector_field(0, BluefiReply, wifiCredentials, WifiCredentials_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* BLUEFI_READER_H */
