#ifndef LOGGER_VERIFIER_H
#define LOGGER_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef LOGGER_READER_H
#include "logger_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int LoggerCommand_verify_table(flatcc_table_verifier_descriptor_t *td);
static int LoggerReply_verify_table(flatcc_table_verifier_descriptor_t *td);

static int LoggerCommand_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* loggerCommandType */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* parameter */)) return ret;
    return flatcc_verify_ok;
}

static inline int LoggerCommand_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, LoggerCommand_identifier, &LoggerCommand_verify_table);
}

static inline int LoggerCommand_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, LoggerCommand_type_identifier, &LoggerCommand_verify_table);
}

static inline int LoggerCommand_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &LoggerCommand_verify_table);
}

static inline int LoggerCommand_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &LoggerCommand_verify_table);
}

static int LoggerReply_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_vector_field(td, 0, 0) /* fileList */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* fileContent */)) return ret;
    return flatcc_verify_ok;
}

static inline int LoggerReply_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, LoggerReply_identifier, &LoggerReply_verify_table);
}

static inline int LoggerReply_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, LoggerReply_type_identifier, &LoggerReply_verify_table);
}

static inline int LoggerReply_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &LoggerReply_verify_table);
}

static inline int LoggerReply_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &LoggerReply_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* LOGGER_VERIFIER_H */
